# Generated by Django 4.1.13 on 2024-02-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Userprofile', '0001_initial'),
        ('Restaurant', '0002_alter_restaurant_restaurantid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_address', models.TextField(default='')),
                ('delivery_groupid', models.IntegerField(blank=True, null=True)),
                ('restaurantid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.restaurant')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userprofile.user')),
            ],
        ),
    ]
