# Generated by Django 4.1.13 on 2024-02-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('password', models.TextField(default='default_password', max_length=100)),
                ('address', models.TextField(default='default_address')),
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
